---
engines:
  brakeman:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.rb"
  - "**.rake"
exclude_paths:
- db/
- spec/
